### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by andreashe** [doherty/Lingua-Boolean#3]
# cpanm Lingua::Boolean

--> Working on Lingua::Boolean
Fetching http://search.cpan.org/CPAN/authors/id/D/DO/DOHERTY/Lingua-Boolean-0.005.tar.gz ... OK
Configuring Lingua-Boolean-0.005 ... N/A
! Configure failed for Lingua-Boolean-0.005. See /root/.cpanm/build.log for details.

---

cpanm (App::cpanminus) 1.0015 on perl 5.010000 built for i486-linux-gnu-thread-multi
Work directory is /root/.cpanm/work/1291136466.31606
You have make /usr/bin/make
You have LWP 5.834
You have /bin/tar: tar (GNU tar) 1.20
Copyright © 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL Version 3 oder später http://gnu.org/licenses/gpl.html
Dies ist freie Software: Sie dürfen sie ändern und weiter verbreiten.
Es gibt KEINERLEI GARANTIE, so weit das Gesetz es erlaubt.

Geschrieben von John Gilmore und Jay Fenlason.
You have /usr/bin/unzip
Searching Lingua::Boolean on cpanmetadb ...
--> Working on Lingua::Boolean
Fetching http://search.cpan.org/CPAN/authors/id/D/DO/DOHERTY/Lingua-Boolean-0.005.tar.gz
-> OK
Unpacking Lingua-Boolean-0.005.tar.gz
Entering Lingua-Boolean-0.005
Checking if you have ExtUtils::MakeMaker 6.31 ... Yes (6.56)
Configuring Lingua-Boolean-0.005
Running Makefile.PL
Perl v5.10.1 required--this is only v5.10.0, stopped at Makefile.PL line 5.
BEGIN failed--compilation aborted at Makefile.PL line 5.
-> N/A
-> FAIL Configure failed for Lingua-Boolean-0.005. See /root/.cpanm/build.log for details.

Maybe a older Perl is also ok? (Perl v5.10.1 required--this is only v5.10.0)

**Comment by doherty** [comment]
You'll need Perl 5.10.1.

**Comment by andreashe** [comment]
I know. But why? It is just a simple string thing. I cant update my perl. So I would consider writing an own class what does exactly the same, but takes also older perl :-(

**Comment by doherty** [comment]
It isn't string comparison. It compares your string to an arrayref of regexes. Smart matching makes that easy, and I refuse to do it the hard way. You should understand this module is an experiment, and the implementation is in alpha. If you still want to use it, you'll just have to live with the dependencies.

**Comment by andreashe** [comment]
ok but a comparision to regex is also what I mean. i would do it the same way. Is realy a newer perl needed just for doing such a simple thing?

Is that the line which needs new perl?

return true if ($to_test ~~ $self->{languages}->{$lang}->{match}->{True});

kinda quick array compare? hmm, maybe its possible to check perl version and do a old style loop when old perl?

.. or is it a different line?

**Comment by doherty** [comment]
Yes, that's the smart matching I'm referring to. If you want it to work on older perls, you can't use smart matching. It can be done, I simply prefer not to. I just don't really care about perls older than 5.10.1.

Patches welcome, I guess, but for right now, I'm comfortable requiring 5.10.1.

**Comment by andreashe** [comment]
I like the rest, except the dependency to strig::trim ... which is also simple ;-)

Do you know how to get perl's version via perl during runtime?

**Comment by doherty** [comment]
Yes, I do, however I don't have any particular wish to support older perls.

**Comment by andreashe** [comment]
ok. So I released a simple similar class: http://search.cpan.org/~ahernit/String-Boolean-0.01/lib/String/BooleanSimple.pm
