### ISSUE TITLE
Test failures due to hash randomisation in perl 5.17.6

### ISSUE THREAD

**Issue by andk** [doherty/Lingua-Boolean#4]
Since bleadperl v5.17.5-518-g7dc8663 your tests are failing frequently.
That commit introduced hash key randomization and it seems at least the test

t/00-init.t

is hit by that. My failing smoke reports have not yet arrived at cpantesters; see a ample from the diagnostics I got:

```
#   Failed test 'Available language codes OK'
#   at t/00-init.t line 27.       
#     Structures begin differing at:
#          $got->[0] = 'fr'       
#     $expected->[0] = 'en'

#   Failed test 'Available language names OK'
#   at t/00-init.t line 32.
#     Structures begin differing at:
#          $got->[0] = 'Fran�ais'
#     $expected->[0] = 'English'
# Looks like you failed 2 tests of 4.

#   Failed test 'oo'
#   at t/00-init.t line 34.

  #   Failed test 'Available language codes OK'
  #   at t/00-init.t line 40.
  #     Structures begin differing at:
  #          $got->[0] = 'fr'
  #     $expected->[0] = 'en'

  #   Failed test 'Available language names OK'
  #   at t/00-init.t line 45.
  #     Structures begin differing at:
  #          $got->[0] = 'Fran�ais'
  #     $expected->[0] = 'English'
  # Looks like you failed 2 tests of 2.

#   Failed test 'func'
#   at t/00-init.t line 47.
# Looks like you failed 2 tests of 3.
```

  t/00-init.t ..... 
  Dubious, test returned 2 (wstat 512, 0x200)
  Failed 2/3 subtests 

You can read more about the commit at
http://perl5.git.perl.org/perl.git/commit/7dc8663964c66a698d31bbdc8e8abed69bddeec3

You may have to run the test several times until the randomization causes a fail.

HTH&&Thanks&&Regards,

**Comment by doherty** [comment]
Thank you for your help. I've attempted to fix this in 4481736ab436b99c170223047010b7f8bfa740d3, and the tests seem to pass on both sides of the commit you mentioned.
